### ISSUE TITLE
Script to stop FlexUnlimited.py at a specified date and time

### ISSUE THREAD

**Issue by ghost** [mdesilva/AmazonFlexUnlimited#130]
I wrote a script that starts the FlexUnlimited but I can stop it att the end of the script. Can someone help me with the command ?

**Comment by simonpacis** [comment]
Hi,

My fork of Flex Unlimited supports this. Please see README.md for instructions.

https://github.com/simonpacis/AmazonFlexUnlimitedSUPERCHARGED

Simon

**Comment by ghost** [comment]
Thanks

**Comment by simonpacis** [comment]
If you're looking for just the code for this, here you go:

Add the following **after** line 88 (```self.session = requests.Session()```):

```python
        self.stopRunAt = config['stopRunAt']
        self.start_time = int(datetime.today().timestamp())
```

Add the following **before** line 463 (```time.sleep(self.refreshInterval)```):

```python

      if type(self.stopRunAt) is str: 
           cur_date = datetime.today().strftime('%Y-%m-%d')
           end_time = int(datetime.strptime(cur_date + " " + self.stopRunAt, "%Y-%m-%d %H:%M").timestamp())
           cur_time = int(datetime.today().timestamp())
           if((self.start_time < end_time) and (cur_time > end_time)):
               Log.info("Block search stopped due to stopRunAt setting.")
               exit()
```

Add the following to config.json:

```json
...
   "stopRunAt": false
...
```

Set stopRunAt to the H:M you want the script to stop. So, for 5:22 PM it is "17:22".

**Comment by ghost** [comment]
Thanks 😊 Hey I has one more question I signed up with ntfy.sh but in the field ntfyChannel I’m not sure what to enter so I’ll get a text message when an offer is accepted.  Sent from Mail for Windows From: Simon PacisSent: Saturday, May 27, 2023 1:01 PMTo: mdesilva/AmazonFlexUnlimitedCc: jddms2; AuthorSubject: Re: [mdesilva/AmazonFlexUnlimited] Script to stop FlexUnlimited.py at a specified date and time (Issue #130) If you're looking for just the code for this, here you go:Add the following after line 88:        self.stopRunAt = config['stopRunAt']        self.start_time = int(datetime.today().timestamp())Add the following before line 463:      if type(self.stopRunAt) is str:            cur_date = datetime.today().strftime('%Y-%m-%d')           end_time = int(datetime.strptime(cur_date + " " + self.stopRunAt, "%Y-%m-%d %H:%M").timestamp())           cur_time = int(datetime.today().timestamp())           if((self.start_time < end_time) and (cur_time > end_time)):               Log.info("Block search stopped due to stopRunAt setting.")               exit()Add the following to config.json:...   "stopRunAt": false...Set stopRunAt to the H:M you want the script to stop. So, for 5:22 PM it is "17:22".—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by simonpacis** [comment]
Hi,

I think it's actually called a subscription, so I should probably rename it. But see photos below for how to create a new one.

First, click plus in upper right hand corner.

![image](https://github.com/mdesilva/AmazonFlexUnlimited/assets/7118482/5dec3fa6-be8c-4046-ae8a-b6f044e80dcc)

![image](https://github.com/mdesilva/AmazonFlexUnlimited/assets/7118482/cd51d525-efab-40a3-855f-b7f11db80c9a)

![image](https://github.com/mdesilva/AmazonFlexUnlimited/assets/7118482/4d2dc515-e04b-4cff-a61b-90e8707571c6)

All the best,
Simon

**Comment by username007-7** [comment]
Hello Simon, 
Thanks for providing a fork with CAPTCHA detection option. 
I tried running your script and got the following execution error:

Traceback (most recent call last):

File "app.py", line 6, in <module> flexUnlimited = FlexUnlimited()

File "/root/AmazonFlexUnlimitedSUPERCHARGED-master/lib/FlexUnlimited.py", line 73, in __init_ config= json. load (configFile)

File "/usr/lib/python3.7/json/__init__.py", line 296, in load parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)

File "/usr/lib/python3.7/json/__init__.py", line 348, in loads return _default_decoder.decode(s)

File "/usr/lib/python3.7/json/decoder.py", line 340, in decode raise JSONDecodeError("Extra data", s, end)

json.decoder.JSONDecodeError: Extra data: line 28 column 2 (char 1258) root@localhost:~/AmazonFlexUnlimitedSUPERCHARGED-master#

Do you have any idea of what may be to fix it? 
Rogi

**Comment by username007-7** [comment]
> Hi,
> 
> My fork of Flex Unlimited supports this. Please see README.md for instructions.
> 
> https://github.com/simonpacis/AmazonFlexUnlimitedSUPERCHARGED
> 
> Simon


Hello Simon, @simonpacis 
Thanks for providing a fork with CAPTCHA detection option and android notification (ntfy). 
I tried running your script and got the following execution error:

Traceback (most recent call last):

File "app.py", line 6, in <module> flexUnlimited = FlexUnlimited()

File "/root/AmazonFlexUnlimitedSUPERCHARGED-master/lib/FlexUnlimited.py", line 73, in __init_ config= json. load (configFile)

File "/usr/lib/python3.7/json/__init__.py", line 296, in load parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)

File "/usr/lib/python3.7/json/__init__.py", line 348, in loads return _default_decoder.decode(s)

File "/usr/lib/python3.7/json/decoder.py", line 340, in decode raise JSONDecodeError("Extra data", s, end)

json.decoder.JSONDecodeError: Extra data: line 28 column 2 (char 1258) root@localhost:~/AmazonFlexUnlimitedSUPERCHARGED-master#

Do you have any idea of what may be to fix it? 
Rogi

**Comment by sack2116** [comment]
> > Hi,
> > My fork of Flex Unlimited supports this. Please see README.md for instructions.
> > https://github.com/simonpacis/AmazonFlexUnlimitedSUPERCHARGED
> > Simon
> 
> Hello Simon, @simonpacis Thanks for providing a fork with CAPTCHA detection option and android notification (ntfy). I tried running your script and got the following execution error:
> 
> Traceback (most recent call last):
> 
> File "app.py", line 6, in flexUnlimited = FlexUnlimited()
> 
> File "/root/AmazonFlexUnlimitedSUPERCHARGED-master/lib/FlexUnlimited.py", line 73, in __init_ config= json. load (configFile)
> 
> File "/usr/lib/python3.7/json/**init**.py", line 296, in load parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
> 
> File "/usr/lib/python3.7/json/**init**.py", line 348, in loads return _default_decoder.decode(s)
> 
> File "/usr/lib/python3.7/json/decoder.py", line 340, in decode raise JSONDecodeError("Extra data", s, end)
> 
> json.decoder.JSONDecodeError: Extra data: line 28 column 2 (char 1258) root@localhost:~/AmazonFlexUnlimitedSUPERCHARGED-master#
> 
> Do you have any idea of what may be to fix it? Rogi

did you get this resolved? im having gthe same issue

**Comment by simonpacis** [comment]
Try to send your config.json (without username and password and tokens), then I’ll take a look.

**Comment by rokipet** [comment]
@simonpacis  im using your scrip is awsome any way we could make a interface with this or run the scrip by discord or get the notifications by telegram ?

**Comment by simonpacis** [comment]
Hi @rokipet,

Please create a new issue for this feature request on my fork. This is the OG Amazon Flex Unlimited

However, as for my fork, I have no plans for either at the moment, as I use neither of these services, but we can discuss it in a separate issue. 

Simon

**Comment by rokipet** [comment]
@simonpacis i got a question when the bot gets a offer  im getting  a request returned satus code 410 on the notification what this mean ?? also it says unable to accept an offer

**Comment by simonpacis** [comment]
Hi @rokipet 

Please create a new issue for this. Thanks.

**Comment by simonpacis** [comment]
> @simonpacis i got a question when the bot gets a offer im getting a request returned satus code 410 on the notification what this mean ?? also it says unable to accept an offer

This is not my fork. Please create an issue on my fork, if you have questions for me. Thanks!

**Comment by sack2116** [comment]
> Try to send your config.json (without username and password and tokens), then I’ll take a look.

here is the cofig file...
{
  "username": "test",
  "password": "test",
  "minBlockRate": 118,
  "minPayRatePerHour": 28.5,
  "arrivalBuffer": 45,
  "desiredWarehouses": [
    "16fc06b5-5504-4dbc-9146-b5f262340e43"
  ],
  "desiredStartTime": "00:02",
  "desiredEndTime": "23:58",
  "desiredWeekdays": [
    "MON",
    "tue",
    "Wed",
    "Thur",
    "Fri",
    "Sunday"
  ],
  "retryLimit": 10,
  "refreshIntervalMin": 0.2,
  "refreshIntervalMax": 2,
  "twilioAcctSid": "test",
  "twilioAuthToken": "test",
  "twilioFromNumber": "+test",
  "twilioToNumber": "+test",
  "refreshToken": "",
  "accessToken": ""
"ntfyChannel": "",
	"filterForWarehouse": true,
	"stopRunAt": false,
	"logging": {
		"notice": true,
		"info": true,
		"success": true,
		"error": true
	},
	"notifications": {
		"notice": false,
		"info": false,
		"success": true,
		"error": true
	},
	"rateLimit": {
		"increment": 30,
		"maxTimesIncrement": 4
	}
}

**Comment by rokipet** [comment]
@simonpacis  i dont why the reason i cant  create a issue on your proyect ?
