### ISSUE TITLE
Offers are not displayed!

### ISSUE THREAD

**Issue by ransel2016** [mdesilva/AmazonFlexUnlimited#135]
Good morning, I'm having problems that sometimes there are blocks in the Flex app and I put the bot to grab them at base payment and it doesn't see them or grab them, I already did a trace of the code and it always shows the code 200 but the value of currentOffers = offersResponse.json().get("offerList") is empty and the block remains on the screen, I don't know if it is a disconnection of the script and the API but it is happening to me often and today at dawn it happened from 12 to 2 am. If anyone is going through the same thing please I would like to discuss the issue. Greetings to all

**Comment by username007-7** [comment]
I can't exactly tell you I am going through the same issue bc I haven't trace the code. May I ask you what are you using to trace the code back? So I can give you a concrete answer. 
The reason to comment here is: when I change the minPayRatePerHour in config.json to 15, it SHOULD grab at least a block or two but it doesn't. 
Also, I've been running a fork by Simon, link bellow, which has more features and improvements, and show real time offers being print on terminal. It behaves the same as the main source script however I can tell my credential and rest of the script body, as far as the structure works such as tokens, credentials, offers found.  but again, it SHOULD but it does not, grab this offer after changing the pay rate hour to 15...

[2023-07-21 11:17:51.025086] NOTICE: Found the following offer (now sleeping 1.76s):
[2023-07-21 11:17:51.025284] NOTICE: Location: 11a28d2c-9e2a-4c92-b3db-9744403d2378
Date: 7/21
Pay: 72.0
Pay rate per hour: 18.0
Block Duration: 4.0hours
Start time: 1245
End time: 1645

https://github.com/simonpacis/AmazonFlexUnlimitedSUPERCHARGED

@simonpacis, do you have any input about this issue?

**Comment by simonpacis** [comment]
Hey!

Let’s try to debug this. couple of things.

1) do you have “11a28d2c-9e2a-4c92-b3db-9744403d2378” in your “desiredWarehouses” array in config.json?
2) What is your “filterForWarehouse” setting?
3) What is your “minBlockRate” setting?
4) Is “Fri” in your “desiredWeekdays” array?
5) What is your “desiredStartTime” and “desiredEndTime”?

Simon

**Comment by username007-7** [comment]
Thanks for your quick response. Everything is left on default. Because I wasn't getting any blocks booked I only change the per hour rate to 15. So I would assume to grab any blocks that are available that pay anything above that price.  I am pasting some of that info for your review from config.json file. 

"minBlockRate": 150,
  "minPayRatePerHour": 32,
  "arrivalBuffer": 45,
  "desiredWarehouses": [],
  "desiredStartTime": "00:00",
  "desiredEndTime": "23:30",
  "desiredWeekdays": [
    "Mon",
    "Tue",
    "Wed",
    "Thur",
    "Fri",
    "Sat",
    "Sun"
  ],
  "retryLimit": 0,
  "refreshIntervalMin": 0.2,
  "refreshIntervalMax": 2,
  "twilioAcctSid": "",
  "twilioAuthToken": "",
  "twilioFromNumber": "",
  "twilioToNumber": "",

**Comment by simonpacis** [comment]
> I only change the per hour rate to 15. So I would assume to grab any blocks that are available that pay anything above that price.

Indeed, but pay attention to the "minBlockRate"-setting, which is 150. The block offered by Amazon has to total 150 for the script to accept it, even if the hourly pay rate is on our below your minPayRatePerHour. On top of this, you do not have the warehouse id in your "desiredWarehouses"-array. I would assume your config.json should look like this (set minBlockRate to 1 so that all blocks are accepted, despite their total rate):

```json
"minBlockRate": 1,
"minPayRatePerHour": 15,
...
"desiredWarehouses": ["11a28d2c-9e2a-4c92-b3db-9744403d2378"],
...
```

Try it, and see if the script will accept an offer now.

**Comment by username007-7** [comment]
Gotcha Ya! Thanks for that. I believed the minBlockRate to be a parameter as of for the minutes. 150 = 2.5 hours. But it all makes sense. I will play with the values.

**Comment by simonpacis** [comment]
@username007-7 No problem! Don't hesitate to reach out if you stumble into other things. While it is not my script, I've gotten to know it by now.

As for AFUSUPERCHARGED, I think the next addition is for the script to explain why it has chosen not to accept a given offer.

**Comment by username007-7** [comment]
@simonpacis THANKS SO MUCH. It WORKS.  I've been trying to get this to work for a while now.  Just booked a 30/hour block - very happy with it. I am running on a server that offers 1.5gb/s download speeds and half gib upload. Ionos Vps Xs if you want to check it out. $2/month

@ransel2016 I guess in order to have the script working out of the bat, you may have to change the minBlockRate to 1 and perhaps desiredWareHouses to one you can find the list, by reading README notes

**Comment by username007-7** [comment]
@simonpacis, I do have one more inquiry. So far the script works, books me blocks and notifies. Although, it seems to get stuck on a loop when it reaches the Rate limit threshold. Having my "RetryLimit" parameter set to "0".
Is there a way to run the script for an indefinite time without Rate limit option?
I've lower-raised the Rate numbers in config.json file, but even so, every time I exit out of  (CTRL + "c") the script and re-run, it loops right-a-way into "rate limit reached"...




[2023-07-22 16:53:01.168109] NOTICE: Rate limit reached. Waiting for 30 minutes.
^CTraceback (most recent call last):
  File "/home/tmp/Desktop/AmazonFlexUnlimitedSUPERCHARGED-master/app.py", line 15, in <module>
    flexUnlimited.run()
  File "/home/tmp/Desktop/AmazonFlexUnlimitedSUPERCHARGED-master/lib/FlexUnlimited.py", line 513, in run
    time.sleep(minutes_to_wait * 60)
KeyboardInterrupt

root@Debian10-1gb:/home/tmp/Desktop/AmazonFlexUnlimitedSUPERCHARGED-master#
root@Debian10-1gb:/home/tmp/Desktop/AmazonFlexUnlimitedSUPERCHARGED-master# python3 app.py
***Amazon Flex Unlimited SUPERCHARGED***

[2023-07-22 16:53:15.095697] NOTICE: Starting block search.
[2023-07-22 16:53:15.160651] INFO: Found 0 new offer(s), sleeping 0.93s.
[2023-07-22 16:53:16.147254] INFO: Found 0 new offer(s), sleeping 0.84s.
[2023-07-22 16:53:17.049521] INFO: Found 0 new offer(s), sleeping 0.37s.
[2023-07-22 16:53:17.479991] INFO: Found 0 new offer(s), sleeping 0.69s.
[2023-07-22 16:53:18.201562] NOTICE: Rate limit reached. Waiting for 30 minutes.

**Comment by simonpacis** [comment]
I think a clarification will help clear up the confusion.

First, it is Amazon that rate limits your script. Essentially, they see that your script is making a lot of requests in a short amount of time, so they limit the rate at which your script can send requests. If you continue sending requests at the same rate, it is unlikely that they will lift the limit.

Therefore, the script employs two measures to prevent being rate limited:

1) refreshInterval. How often the script checks for new blocks. The higher you set this, the less likely you are to be limited. This is a balancing act, since you want it to refresh often enough to catch blocks before other people.

2) The sleep mechanism. When the script notices that it has been rate limited, it sleeps first for 30 minutes. The next time it notices it has been rate limited, it sleeps for 60 minutes. The next time 90, then 120, and then it resets back to 30. In my fork, these defaults can be changed through the rateLimit.increment (minutes to sleep), and rateLimit.maxTimesIncrement (how many times to * rateLimit.increment before resetting to 1) settings. This is all in an attempt to lift the rate limit imposed upon the script by Amazon.

So, to answer you question:

> Is there a way to run the script for an indefinite time without Rate limit option?

No. The rate limit is imposed upon the script by Amazon. We do not control it, we try to prevent it.

The best way to run it indefinitely is to either

1) Increase your refreshInterval (E.g. min 0.2, max 4.0)

2) Play around with the rate limit settings to see if you can find something that gets you limited less than with the default settings.

> I've lower-raised the Rate numbers in config.json file, but even so, every time I exit out of (CTRL + "c") the script and re-run, it loops right-a-way into "rate limit reached"...

And this happens because Amazon has rate limited you. The script is going to sleep and hoping the limit is gone when it wakes up. You restarting the script does not lift the limit, unfortunately.

I hope that all makes sense!

**Comment by username007-7** [comment]
Thank you so much for your clear explanation about the rate limit and how it is implicitly imposed by Amazon. It all makes sense to me now. Your insights have been invaluable, and I appreciate the time you took to help me understand this better.

**Comment by zmkaihan** [comment]
@ransel2016  I'm facing the same problem there are blocks in the real app but script shows 0 offers did you find any solution for it, please let me know! @mdesilva  Do you have time to look at the issue please?
