### ISSUE TITLE
More of a feature request…

### ISSUE THREAD

**Issue by tbstewa** [mdesilva/AmazonFlexUnlimited#15]
Would it be possible to set a Max block length? Like say I only want to work a 3 hour block? I know I can set start and end hours

**Comment by sack2116** [comment]
This would be nice to have.... if someone knows of a way pls share..

**Comment by omar-ramo** [comment]
in config.json add this  line:
`maxBlockDuration: 5,
`
in FlexUnlimited.py inside the __init__ function around line 89 add:
`self.maxBlockDuration = config["maxBlockDuration"]`

in FlexUnlimited.py inside the  __processOffer add another if clause:
```
if self.maxBlockDuration:
      if (offer.endTime - offer.expirationDate) / 3600 >  self.maxBlockDuration:
        return
```

**Comment by cpietrobelli** [comment]
Traceback (most recent call last):
  File "/home/skynet/amzflex/cp/cajas/app.py", line 15, in <module>
    flexUnlimited.run()
  File "/home/skynet/amzflex/cp/cajas/lib/FlexUnlimited.py", line 454, in run
    self.__processOffer(offerResponseObject)
  File "/home/skynet/amzflex/cp/cajas/lib/FlexUnlimited.py", line 419, in __processOffer
    if (offer.endTime - offer.expirationDate) / 3600 >  self.maxBlockDuration:
TypeError: '>' not supported between instances of 'datetime.timedelta' and 'int'

**Comment by beewax** [comment]
Hi all,  
Has anyone been successful with adding block length?
 I tried adding the code as instructed but it just breaks the whole script. Thank you.

**Comment by omar-ramo** [comment]
Try this 
```
if self.maxBlockDuration:
      if (offer.endTime - offer.startTime).seconds / 3600 >  self.maxBlockDuration:
        return
```
I proposed the solution before without testing it because personaly I had no use for it, I tried it now and it seemed to work as excpected.

If you don't have the up-to-date version of the repository, They have added the `startTime` property to the offer object in the `Offer.py` because `expirationDate` was causing problems with reserved offers.

**Comment by beewax** [comment]
I really appreciate your feedback and contribution.
I updated all the packages, downloaded the new amazon flex unlimited and copied the updated scripts but still it unexpectedly quits.
 I am on windows 10 and not a programmer. Your help is appreciated.
