### ISSUE TITLE
Error when loggin

### ISSUE THREAD

**Issue by blackfire1993** [mdesilva/AmazonFlexUnlimited#32]
Hi, i try to run but i am getting this error, any idea?

Traceback (most recent call last):
  File "/home/server/amz/./lib/FlexUnlimited.py", line 122, in __getFlexRequestAuthToken
    return response.get("response").get("success").get("tokens").get("bearer").get("access_token")
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):

  File "/home/server/amz/app.py", line 5, in <module>
    flexUnlimited = FlexUnlimited()
  File "/home/server/amz/./lib/FlexUnlimited.py", line 70, in __init__
    self.__requestHeaders["x-amz-access-token"] = self.__getFlexRequestAuthToken()
  File "/home/server/amz/./lib/FlexUnlimited.py", line 128, in __getFlexRequestAuthToken
    sys.exit()
SystemExit

**Comment by bessaoudi** [comment]
hi,
try to do that, go to "auth.sh" look for password and username and change them with yours.

**Comment by mdesilva** [comment]
Make sure you are running python version 3 or above. You can check your version using the command `python --version`.

**Comment by mdesilva** [comment]
Alternatively, you can try running `python3 app.py`, as python3 might be installed independently of your systems python distribution. If that fails, install python 3 onto your system and try again.

**Comment by mdesilva** [comment]
Alternatively, you can try running `python3 app.py`, as python3 might be installed independently of your systems python distribution. If that fails, install python 3 onto your system and try again.

**Comment by blackfire1993** [comment]
Hey thank you for answering me, it was given me that error because I was running the script without the python command first, and also I found a better way to sign in, I put OTP authentication on my amazon account, and then I made a modification in the script to ask me for the OTP code when you run, then you input the code and the app try to login again adding the code at the end of the password.

**Comment by samkhazi** [comment]
Can u please send me the complete code on my mail ( samkhazi25@gmail.com )

**Comment by mdesilva** [comment]
@blackfire1993 That sounds very useful. Can you make a pull request against this repo so I can take a look ?

**Comment by blackfire1993** [comment]
> @blackfire1993 That sounds very useful. Can you make a pull request against this repo so I can take a look ?

Hey @mdesilva  I'm not pretty sure how the github app works but i will let you here the modification that i did

is just in the exception when you try to  log in

```
      twoStepVerificationChallengeUrl = self.__getTwoStepVerificationChallengeUrl(response)
      #print(f"\nPlease try completing the two step verification challenge at \033[1m{twoStepVerificationChallengeUrl}\033[0m . 
      Then try again.")
      print("Unable to authenticate to Amazon Flex.")
      x = input("Enter the OTP CODE\n\n")
      payload['auth_data']['user_id_password']['password'] = payload['auth_data']['user_id_password']['password'] + x
      
      
      try:
        response: Response = requests.post(FlexUnlimited.routes.get("GetAuthToken"),
                               headers=FlexUnlimited.allHeaders.get("AmazonApiRequest"), json=payload).json()
        return response.get("response").get("success").get("tokens").get("bearer").get("access_token")
      except Exception as e:
      
        print("Unable to authenticate to Amazon Flex with your OTP")
        sys.exit()
```

**Comment by samkhazi** [comment]
I'm getting error of 403 while trying to get Auth token... I've tried two step verification too but no luck.
Is it because of the account I'm using belongs to India ?
If so how to find routes of Indian server. Please resolve
