### ISSUE TITLE
getAllServiceAreas error

### ISSUE THREAD

**Issue by ademircan** [mdesilva/AmazonFlexUnlimited#56]
I run `python3 app.py getAllServiceAreas` to get warehouse ids' but returns an error.

```
Amazon Flex Unlimited v2

 Your service area options:
Traceback (most recent call last):
  File "D:\AmazonFlexUnlimited-master\AmazonFlexUnlimited-master\app.py", line 11, in <module>
    print(flexUnlimited.getAllServiceAreas())
  File "D:\AmazonFlexUnlimited-master\lib\FlexUnlimited.py", line 177, in getAllServiceAreas
    for serviceArea in serviceAreaPoolList:
TypeError: 'NoneType' object is not iterable
PS D:\Chrome\Downloads\AmazonFlexUnlimited-master\AmazonFlexUnlimited-master>
```

Does anyone have an idea how to sort this out?

**Comment by ademircan** [comment]
Solved.

Routes are set for USA I believe. I used Charles Proxy to see which Amazon domain I am making request to and realised domains are 'jp' not 'na' for Australia.
