### ISSUE TITLE
not able to sign in 

### ISSUE THREAD

**Issue by Brububabu111** [mdesilva/AmazonFlexUnlimited#80]

**Comment by Brububabu111** [comment]
I pasted the code but FIRST Mac doest let me input more than 1024 chars and then I tried 


python3 app.py


***Amazon Flex Unlimited v2*** 

Link: https://www.amazon.com/ap/signin?ie=UTF8&clientContext=134-9172090-0857541&openid.pape.max_auth_age=0&use_global_authentication=false&accountStatusPolicy=P1&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&use_audio_captcha=false&language=en_US&pageId=amzn_device_na&arb=97b4a0fe-13b8-45fd-b405-ae94b0fec45b&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.assoc_handle=amzn_device_na&openid.oa2.response_type=token&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&disableLoginPrepopulate=0&openid.oa2.client_id=device%3A32663430323338643639356262653236326265346136356131376439616135392341314d50534c4643374c3541464b&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
Open the previous link (make sure to copy the entire link) in a browser, sign in, and enter the entire resulting URL here:
with open('text.txt', 'r') as f:
    text = f.read()
    # process the text
Traceback (most recent call last):
  File "/Users/brunadowling/AmazonFlexUnlimited/app.py", line 6, in <module>
    flexUnlimited = FlexUnlimited()
  File "/Users/brunadowling/AmazonFlexUnlimited/lib/FlexUnlimited.py", line 110, in __init__
    self.__registerAccount()
  File "/Users/brunadowling/AmazonFlexUnlimited/lib/FlexUnlimited.py", line 143, in __registerAccount
    reg_access_token = unquote(parsed_query['openid.oa2.access_token'][0])
KeyError: 'openid.oa2.access_token'
brunadowling@brunas-mbp AmazonFlexUnlimited %     text = f.read()
function>     # process the text
brunadowling@brunas-mbp AmazonFlexUnlimited %

**Comment by Brububabu111** [comment]
As you see I tried calling from with open('text.txt', 'r') as f:
    text = f.read()
    # process the text
    
    It didn't work
    
     can someone HELP PLEASE

**Comment by ademircan** [comment]
Did you try to use different terminal such as like iTerm2, zsh?

**Comment by Brububabu111** [comment]
I didn't

**Comment by Nguy3nImprovd** [comment]
I have the same issue where the return URL does not contain "openid.oa2.access_token" as part of his key.

**Comment by sack2116** [comment]
was there a solution here?
