### ISSUE TITLE
issues?

### ISSUE THREAD

**Issue by ronaldjm2** [mdesilva/AmazonFlexUnlimited#9]
after trying to run app.py I'm getting these errors:
Traceback (most recent call last):
  File "C:\Users\Owner\Documents\GitHub\AmazonFlexUnlimited\app.py", line 5, in <module>
    flexUnlimited = FlexUnlimited()
  File "C:\Users\Owner\Documents\GitHub\AmazonFlexUnlimited\lib\FlexUnlimited.py", line 54, in __init__
    config = json.load(configFile)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 3 column 3 (char 54)

Do you know why this could be? I've been looking at the code and everything looks good to me

**Comment by mdesilva** [comment]
@ronaldjm2 Have you edited the `config.json` file ? If so make sure to match the formatting in the sample config file. Any missing `"` characters or `:` will throw an error.
